# Generated by Django 5.0.2 on 2024-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TimeField(),
        ),
    ]
